services:
  thirdpartyfreight.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
      ASPNETCORE_URLS: https://+:8081;http://+:8080
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: password123
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${USERSECRETS}:/home/app/.microsoft/usersecrets:ro
      - ${ASPHTTPS}:/https:ro
  thirdpartyfreight.web:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./.nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./.nginx/certs:/etc/nginx/certs
  elsa-server:
   environment:
      ASPNETCORE_ENVIRONMENT: Development
      PYTHONNET_PYDLL: /opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/bin/python3.11
      PYTHONNET_RUNTIME: coreclr
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
      ASPNETCORE_URLS: https://+:8081;http://+:8080
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: password123
   ports:
      - "13000:8080"
      - "14001:8081"
   volumes:
      - ${USERSECRETS}:/home/app/.microsoft/usersecrets:ro
      - ${ASPHTTPS}:/https:ro
    