services:
  thirdpartyfreight.api:
    image: ${DOCKER_REGISTRY-}thirdpartyfreightapi
    container_name: ThirdPartyFreight.Api
    build:
      context: .
      dockerfile: src/ThirdPartyFreight.Api/Dockerfile
    ports:
        - "28080:8080"
        - "28081:8081"
  csdtpfblazorwebapp-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: CSDTPFBlazorWebApp.Db
    environment:
      SA_PASSWORD: "SuperHardPassword!!"
      ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes:
        -  ./.containers/database:/var/opt/mssql/data
  csdtpfblazorwebapp-idp:
    build:
        context: .
        dockerfile: keycloak-theme/Dockerfile
    container_name: CSDTPFBlazorWebApp.Identity
    environment:
        KC_DB: postgres
        KC_DB_URL_HOST: postgres-idp-db
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: wfQ6biA$%H4tCJiE1!z7
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: UJxer@fxbf5XE74Q3Y@&
    command:
        - start-dev
    ports:
        - "18080:8080"
    volumes:
        -  ./keycloak-theme/theme/:/opt/keycloak/themes
        -  ./.containers/keycloak/db-data:/opt/keycloak/data
  csdtpfblazorwebapp-seq:
    image: datalust/seq:latest
    container_name: CSDTPFBlazorWebApp.Seq
    environment:
        - ACCEPT_EULA=Y
    ports:
        - "5341:5341"
        - "8081:80"
  csdtpfblazorwebapp-redis:
    image: redis:latest
    container_name: CSDTPFBlazorWebApp.Redis
    ports:
        - "6379:6379"
  elsa-studio:
    image: elsaworkflows/elsa-studio-v3:latest
    container_name: elsa-studio
    depends_on:
      - elsa-server
    environment:
      - HTTP_PORTS=8080
      - ELSASERVER__URL=https://localhost:14001/elsa/api
    ports:
      - "14000:8080"
  thirdpartyfreight.web:
    image: ${DOCKER_REGISTRY-}csdtpfwebapp-thirdpartyfreight.web
    container_name: ThirdPartyFreight.Web
    depends_on:
      - thirdpartyfreight.api
    build:
      context: .
      dockerfile: src/ThirdPartyFreight.Web/Dockerfile
    ports:
      - "80:80"
      - "443:443"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbittmq
    ports:
      - "15672:15672"
      - "5672:5672"
  elsa-server:
    image: ${DOCKER_REGISTRY-}csdtpfwebapp-elsa-server
    container_name: elsa-server
    build:
      context: .
      dockerfile: elsa/ElsaServer/Dockerfile
    depends_on:
      - csdtpfblazorwebapp-db
      - rabbitmq
      - csdtpfblazorwebapp-redis
  postgres-idp-db:
    image: postgres:latest
    container_name: postgres-idp-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: wfQ6biA$%H4tCJiE1!z7
    volumes:
       - ./.containers/postgres-idp-db:/var/lib/postgresql/data