services:
  thirdpartyfreight.api:
    image: ${DOCKER_REGISTRY-}thirdpartyfreightapi
    container_name: ThirdPartyFreight.Api
    build:
      context: .
      dockerfile: src/ThirdPartyFreight.Api/Dockerfile
    ports:
        - "28080:8080"
        - "28081:8081"
  csdtpfblazorwebapp-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: CSDTPFBlazorWebApp.Db
    environment:
      SA_PASSWORD: "SuperHardPassword!!"
      ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes:
        -  ./.containers/database:/var/opt/mssql/data
  csdtpfblazorwebapp-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: CSDTPFBlazorWebApp.Identity
    environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
        - start-dev
    ports:
        - "18080:8080"
  csdtpfblazorwebapp-seq:
    image: datalust/seq:latest
    container_name: CSDTPFBlazorWebApp.Seq
    environment:
        - ACCEPT_EULA=Y
    ports:
        - "5341:5341"
        - "8081:80"
  csdtpfblazorwebapp-redis:
    image: redis:latest
    container_name: CSDTPFBlazorWebApp.Redis
    ports:
        - "6379:6379"
  elsa-studio:
    image: elsaworkflows/elsa-studio-v3:latest
    container_name: elsa-studio
    environment:
      - HTTP_PORTS=8080
      - ELSASERVER__URL=https://localhost:14001/elsa/api
    ports:
      - "14000:8080"
  thirdpartyfreight.web:
    container_name: ThirdPartyFreight.Web
    build:
      context: .
      dockerfile: src/ThirdPartyFreight.Web/Dockerfile
    ports:
      - "80:80"
      - "443:443"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbittmq
    ports:
      - "15672:15672"
      - "5672:5672"
  elsa-server:
    container_name: elsa-server
    build:
      context: .
      dockerfile: elsa/ElsaServer/Dockerfile
    depends_on:
      - csdtpfblazorwebapp-db
      - rabbitmq
      - csdtpfblazorwebapp-redis
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      PYTHONNET_PYDLL: /opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/bin/python3.11
      PYTHONNET_RUNTIME: coreclr
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
      ASPNETCORE_URLS: https://+:8081;http://+:8080
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/${CertName}
    ports:
      - "13000:8080"
      - "14001:8081"
    volumes:
      - ${USERSECRETS}:/home/app/.microsoft/usersecrets:ro
      - ${ASPHTTPS}:/https:ro