version: '3.4'

services:
  thirdpartyfreight.api:
    image: ${DOCKER_REGISTRY-}thirdpartyfreightapi
    container_name: ThirdPartyFreight.Api
    build:
      context: .
      dockerfile: src/ThirdPartyFreight.Api/Dockerfile
    ports:
        - 28080:8080
        - 28081:8081
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
        - ASPNETCORE_URLS=https://+:8081;http://+:8080
        - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
        - ./src/ThirdPartyFreight.Api/PrivateKeys/aspnetapp.pfx:/https/aspnetapp.pfx:ro  
  csdtpfblazorwebapp-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: CSDTPFBlazorWebApp.Db
    environment:
      SA_PASSWORD: "SuperHardPassword!!"
      ACCEPT_EULA: "Y"
    ports:
        - 1433:1433
    volumes:
        -  ./.containers/database:/var/opt/mssql/data
  csdtpfblazorwebapp-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: CSDTPFBlazorWebApp.Identity
    environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
        - start-dev
    ports:
        - 18080:8080
  csdtpfblazorwebapp-seq:
    image: datalust/seq:latest
    container_name: CSDTPFBlazorWebApp.Seq
    environment:
        - ACCEPT_EULA=Y
    ports:
        - 5341:5341
        - 8081:80
  csdtpfblazorwebapp-redis:
    image: redis:latest
    container_name: CSDTPFBlazorWebApp.Redis
    ports:
        - 6379:6379