CREATE TABLE [dbo].[DIM_CustomerMaster](
       [SITE_USE_ID] [numeric](15, 0) NOT NULL,
       [SITE_USE_STATUS] [varchar](1) NOT NULL,
       [SITE_USE_CODE] [varchar](30) NOT NULL,
       [CUST_STATUS] [varchar](1) NOT NULL,
       [CUST_ACCOUNT_ID] [numeric](15, 0) NOT NULL,
       [CUSTOMER_NUMBER] [varchar](30) NOT NULL,
       [CUSTOMER_NAME] [varchar](360) NOT NULL,
       [CUSTOMER_TYPE] [varchar](30) NULL,
       [CUSTOMER_CLASS_CODE] [varchar](30) NULL,
       [GPO] [varchar](150) NULL,
       [IHN] [varchar](150) NULL,
       [SALES_CHANNEL_CODE] [varchar](30) NULL,
       [OVERALL_CREDIT_LIMIT] [float] NULL,
       [FOB_POINT] [varchar](150) NULL,
       [FREIGHT_TERM] [varchar](150) NULL,
       [LAST_UPDATED] [date] NULL,
       [SITE_NUMBER] [varchar](30) NOT NULL,
       [SITE_STATUS] [varchar](1) NOT NULL,
       [BCI_PRIME_MARKET] [varchar](150) NULL,
       [IDENTIFYING_ADDRESS_FLAG] [varchar](1) NOT NULL,
       [ADDRESS1] [varchar](240) NOT NULL,
       [ADDRESS2] [varchar](240) NULL,
       [ADDRESS3] [varchar](240) NULL,
       [ADDRESS4] [varchar](240) NULL,
       [CITY] [varchar](60) NULL,
       [STATE] [varchar](60) NULL,
       [POSTAL_CODE] [varchar](60) NULL,
       [COUNTY] [varchar](240) NULL,
       [COUNTRY] [varchar](240) NULL,
       [GSA_FLAG] [varchar](5) NULL,
       [ORG_ID] [numeric](15, 0) NULL,
       [LOCATION] [varchar](40) NULL,
       [SITE_FREIGHT_TERM] [varchar](150) NULL,
       [NET_CRITICAL_FLAG] [varchar](240) NULL,
       [CRITICAL_REASON_CODE] [varchar](30) NULL,
       [CRITICAL_REASON_DESC] [varchar](80) NULL,
       [VISN] [varchar](150) NULL,
       [PARTY_SITE_ID] [numeric](15, 0) NULL,
       [TRX_CREDIT_LIMIT] [float] NULL,
       [DXONE_IM] [nvarchar](50) NULL,
       [PARTY_NUMBER] [nvarchar](30) NULL,
       [BCI_OPCO] [varchar](150) NULL,
       [PARTY_TYPE] [varchar](30) NULL,
CONSTRAINT [PK_DIM_CustomerMaster] PRIMARY KEY CLUSTERED 
(
       [SITE_USE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
